// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlvdocoxzmmonprqdmtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsdmRvY294em1tb25wcnFkbXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzk1NjcsImV4cCI6MjA1OTgxNTU2N30.HEZi6qI5rKI4OOadYFnNYm609XpXZAtYwUsp52St-uk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);